name: Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: mac-latest
    steps:
      - uses: actions/setup-python@v5
      - name: Run a multi-line script
        run: |
          python -c import opensees
